sudo: required
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
before_install:
  - wget https://github.com/jgm/pandoc/releases/download/2.2.1/pandoc-2.2.1-1-amd64.deb
  - sudo dpkg -i pandoc-2.2.1-1-amd64.deb
  - pandoc -v
install:
  - pip install coveralls
  - pip install tox-travis
  - pip install flake8
  - pip install pylint
  - pip install panflute
script:
  - tox
  - flake8 pandoc_numbering.py
  - pylint pandoc_numbering.py
  - coverage run --source=pandoc_numbering setup.py test
  - coverage report -m
after_success:
  - coveralls
