language: python
python:
  - "3.6"
virtualenv:
  system_site_packages: true
before_install:
  - wget https://github.com/jgm/pandoc/releases/download/2.9.2.1/pandoc-2.9.2.1-1-amd64.deb
  - sudo dpkg -i pandoc-2.9.2.1-1-amd64.deb
  - pandoc -v
install:
  - pip install tox
  - pip install coveralls
script:
  - tox
  - coverage report -m
after_success:
  - coveralls
