language: generic
before_install:
  - wget https://github.com/jgm/pandoc/releases/download/2.9.2.1/pandoc-2.9.2.1-1-amd64.deb
  - sudo dpkg -i pandoc-2.9.2.1-1-amd64.deb
  - pandoc -v
  - sudo apt-get install virtualenv
  - audo apt-get install python3.6
  - virtualenv --python=python3.6 venv
  - source venv/bin/activate
  - pip -V
install:
  - pip install coveralls
  - pip install --pre .[test]
script:
  - tox
  - coverage report -m
after_success:
  - coveralls
