language: python
python:
  - "3.6"
before_install:
  - wget https://github.com/jgm/pandoc/releases/download/2.9.2.1/pandoc-2.9.2.1-1-amd64.deb
  - sudo dpkg -i pandoc-2.9.2.1-1-amd64.deb
  - pandoc -v
install:
  - pip install tox
  - pip install coveralls
  - pip install pytest-cov
  - pip install .
script:
  - tox
  - pytest --cov=pandoc_numbering
after_success:
  - coveralls
